# -*- coding: utf-8 -*-
"""List20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEAKmHo7aQbF0UucZHZb6AHhvlD4H9Ky
"""

# list0=['Hello','Everybody','Go','Away']


list1=[1,2,3,4,5,3,4]
largest=max(list1)
list1.remove(largest)
print(max(list1))

