# -*- coding: utf-8 -*-
"""List31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEAKmHo7aQbF0UucZHZb6AHhvlD4H9Ky
"""

from os import remove


# list0=['Hello','Everybody','Go','Away']
# list2=([i for i in list1 if i%2==1])



list1=[1,2,3,4,5,3,4,3]
times=2
repeated = [item for item in list1 for _ in range(times)]
print(repeated)

