# -*- coding: utf-8 -*-
"""List26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEAKmHo7aQbF0UucZHZb6AHhvlD4H9Ky
"""

# list0=['Hello','Everybody','Go','Away']
# list2=([i for i in list1 if i%2==1])


list1=[1,2,3,4,5,3,4,3]
mid=list1[len(list1)//2] if len(list1)%2==1 else (list1[len(list1)//2-1]+list1[len(list1)//2])/2
print(mid)

