# -*- coding: utf-8 -*-
"""List27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEAKmHo7aQbF0UucZHZb6AHhvlD4H9Ky
"""

# list0=['Hello','Everybody','Go','Away']
# list2=([i for i in list1 if i%2==1])



# list1=[1,2,3,4,5,3,4,3]
my_list = [5, 2, 9, 1, 7]
sublist = my_list[1:4]  # Elements at indices 1, 2, 3
max_val = max(sublist)
print(max_val)

