# -*- coding: utf-8 -*-
"""List19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEAKmHo7aQbF0UucZHZb6AHhvlD4H9Ky
"""

# list0=['Hello','Everybody','Go','Away']


list1=[1,2,3,4,5,3,4]
reindex=list1.index(3)
list1[reindex]=6
print(list1)

