# -*- coding: utf-8 -*-
"""List5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEAKmHo7aQbF0UucZHZb6AHhvlD4H9Ky
"""

# 5

# list0=['Hello','Everybody','Go','Away']
# len(list0)

list1=[1,2,3,4,5,3,4]
element=2
exists=element in list1
print(exists)

