# -*- coding: utf-8 -*-
"""List2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEAKmHo7aQbF0UucZHZb6AHhvlD4H9Ky
"""

# 2

# list0=['Hello','Everybody','Go','Away']
# len(list0)

list1=[1,2,3,4,5,3,4]
total=sum(list1)
print(total)

