# -*- coding: utf-8 -*-
"""List40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEAKmHo7aQbF0UucZHZb6AHhvlD4H9Ky
"""

# from os import remove


# list0=['Hello','Everybody','Go','Away']
# list2=([i for i in list1 if i%2==1])



# list1=[1,2,3,4,5,3,4,-3]

my_list = [1, 2, 2, 3, 4, 4, 5]
unique_ordered = list(dict.fromkeys(my_list))
print(unique_ordered)

# print(list2

