# -*- coding: utf-8 -*-
"""List1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEAKmHo7aQbF0UucZHZb6AHhvlD4H9Ky
"""

list0=['Hello','Everybody','Go','Away']
list0.count('Go')

