# -*- coding: utf-8 -*-
"""List35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEAKmHo7aQbF0UucZHZb6AHhvlD4H9Ky
"""

from os import remove


# list0=['Hello','Everybody','Go','Away']
# list2=([i for i in list1 if i%2==1])



# list1=[1,2,3,4,5,3,4,3]

start, end = 1, 5
range_list = list(range(start, end + 1))

