# -*- coding: utf-8 -*-
"""List33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEAKmHo7aQbF0UucZHZb6AHhvlD4H9Ky
"""

from os import remove


# list0=['Hello','Everybody','Go','Away']
# list2=([i for i in list1 if i%2==1])



# list1=[1,2,3,4,5,3,4,3]
# element=3
my_list = [1, 2, 3, 2, 4, 2]
element = 3
indices = [i for i, x in enumerate(list1) if x == element]
print(indices)

