# -*- coding: utf-8 -*-
"""notes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r5wP1OPbY4TVJh8MdFd_2eNXePph0ltp

Functions
Defining Functions
Arguments:
Positional, Keyword
Positional-Only, Keyword-Only
Default
Arbitrary
Lambda Expressions
"""

def intro():
  print("Hello everyone!")

intro()

