# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r5wP1OPbY4TVJh8MdFd_2eNXePph0ltp
"""

def convert_cel_to_far(celsius):
    return celsius * 9/5 + 32

def convert_far_to_cel(fahrenheit):
    return (fahrenheit - 32) * 5/9

f_temp = float(input("Enter a temperature in degrees F: "))
c_temp = convert_far_to_cel(f_temp)
print(f"{f_temp} degrees F = {round(c_temp, 2)} degrees C")

# Prompt for Celsius to Fahrenheit conversion
c_temp = float(input("\nEnter a temperature in degrees C: "))
f_temp = convert_cel_to_far(c_temp)
print(f"{c_temp} degrees C = {round(f_temp, 2)} degrees F")

