# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r5wP1OPbY4TVJh8MdFd_2eNXePph0ltp
"""

def find_factors(n):
    factors = []
    for i in range(1, n + 1):
        if n % i == 0:
            factors.append(i)
    return factors

number = int(input("Enter a positive integer: "))
factors = find_factors(number)

for factor in factors:
    print(f"{factor} is a factor of {number}")

