# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r5wP1OPbY4TVJh8MdFd_2eNXePph0ltp
"""

universities = [
    ['California Institute of Technology', 2175, 37704],
    ['Harvard', 19627, 39849],
    ['Massachusetts Institute of Technology', 10566, 40732],
    ['Princeton', 7802, 37000],
    ['Rice', 5879, 35551],
    ['Stanford', 19535, 40569],
    ['Yale', 11701, 40500]
]

def enrollment_stats(universities):
    students = [u[1] for u in universities]
    tuitions = [u[2] for u in universities]
    return students, tuitions

def mean(lst):
    return sum(lst) / len(lst)

def median(lst):
    sorted_lst = sorted(lst)
    n = len(sorted_lst)
    if n % 2 == 1:
        return sorted_lst[n//2]
    else:
        return (sorted_lst[n//2 - 1] + sorted_lst[n//2]) / 2

students, tuitions = enrollment_stats(universities)

print("******************************")
print(f"Total students: {sum(students):,}")
print(f"Total tuition: $ {sum(tuitions):,}\n")

print(f"Student mean: {mean(students):,.2f}")
print(f"Student median: {median(students):,.0f}\n")

print(f"Tuition mean: $ {mean(tuitions):,.2f}")
print(f"Tuition median: $ {median(tuitions):,.0f}")
print("******************************")

