# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r5wP1OPbY4TVJh8MdFd_2eNXePph0ltp
"""

def invest(amount, rate, years):
    for year in range(1, years + 1):
        amount *= (1 + rate)
        print(f"year {year}: ${round(amount, 2)}")

# Get input
principal = float(input("Enter the principal amount: "))
annual_rate = float(input("Enter the annual rate of return: ")) / 100
years = int(input("Enter the number of years: "))

# print
invest(principal, annual_rate, years)

