# -*- coding: utf-8 -*-
"""boolean4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# boolean4

num1 = int(input("Enter a numb1: "))
num2 = int(input("Enter a numb2: "))
num3 = int(input("Enter a num3: "))
if num1 != num2 and num1!=num3 and num2!=num3:
    print("Numbers are not equal")
else:
    print("Numbers are equal")

3