# -*- coding: utf-8 -*-
"""boolean6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# boolean6

num = int(input("Enter the number: "))
if num%3==0 and num%5==0:
    print("Divisable")
else:
    print("Not divisable")

3