# -*- coding: utf-8 -*-
"""boolean7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# boolean7
def check_sum():
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))
    if num1 + num2 > 50:
        print("Sum is greater than 50")
    else:
        print("Sum is 50 or less")
check_sum()

def check_range():
    num = float(input("Enter a number: "))
    if 10 <= num <= 20:
        print(f"{num} is between 10 and 20")
    else:
        print(f"{num} is not in the range 10-20")

check_range()

15
3