# -*- coding: utf-8 -*-
"""boolean3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# boolean3

num = int(input("Enter the number: "))
if num%2==0 and num>0:
    print("number is positive and even")
else:
    print("Oops")

3