# -*- coding: utf-8 -*-
"""boolean5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# boolean5

str1 = str(input("Enter the first string: "))
str2 = str(input("Enter the second string: "))
if len(str1)==len(str2):
    print("They are equal")
else:
    print("Not equal")

3