# -*- coding: utf-8 -*-
"""boolean1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# boolean

def check_credentials():
    username = input("Enter username: ")
    password = input("Enter password: ")
    if username and password:
        print("Both fields are filled")
    else:
        print("One or both fields are empty")

check_credentials()

