# -*- coding: utf-8 -*-
"""boolean2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# boolean2

num1 = int(input("Enter a numb1: "))
num2 = int(input("Enter a numb2: "))
if num1 == num2:
    print("Numbers are equal")
else:
    print("Numbers are not equal")

