# -*- coding: utf-8 -*-
"""number1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# homework
# number1

num=float(input("Enter a float number " ))
round_num = round(num,2)
print(round_num)