# -*- coding: utf-8 -*-
"""number4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# number4

inp1=int(input("Enter the first number "))
inp2=int(input("Enter the second number "))
result=inp1//inp2
remainder=inp1%inp2

print(f"The quotient is {result} and the remainder is {remainder}")

