# -*- coding: utf-8 -*-
"""number6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# number6

inp=int(input("Enter the number "))

lastDigit=inp%10

print(f"The last digit is {lastDigit}")

