# -*- coding: utf-8 -*-
"""number2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# number2

numb1=(input("Enter the first number " ))
numb2=(input("Enter the second number " ))
numb3=(input("Enter the third number " ))

largest = max(numb1,numb2,numb3)
smallest = min(numb1,numb2,numb3)

print(f"The largest number is ",largest)
print(f"The smallest number is",smallest)

