# -*- coding: utf-8 -*-
"""number3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# number3

inp=float(input("Enter the distance in km "))
meter=inp*1000
print(f"The distance in meter is {meter} m")
sm=inp*100000
print(f"The distance in centimeter is {sm} sm")

