# -*- coding: utf-8 -*-
"""number5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# number5

inp=float(input("Enter the temperature in Celcius: "))

Fahrenheit=(inp*9/5)+32

print(f"The Temperature in Fahrenheit is {Fahrenheit}")

