# -*- coding: utf-8 -*-
"""number7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# number7

inp=int(input("Enter the number "))

if inp%2==0:
    print("The number is even")
else:
    print("The number is odd")

