# -*- coding: utf-8 -*-
"""string13

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# string13
    import string
    text = input("Enter the sentence: ")
    output=text.replace(" ","-"or",")
    print(output)

