# -*- coding: utf-8 -*-
"""string15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# string15
    import string
    text = input("Enter the sentence: ").split()
    acronym = ''.join(word[0].upper() for word in text if word)
    print(acronym)

