# -*- coding: utf-8 -*-
"""string10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# string10
    import string
    text = input("Input the string: ")
    words = text.split()
    print(f"Number of words: {len(words)}")

