# -*- coding: utf-8 -*-
"""string6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# string6
    import string
    text = input("Enter a string: ")
    text_sub=input("Enter the check string ")
    if text_sub in text:
        print("Yes")
    else:
        print("No")

