# -*- coding: utf-8 -*-
"""string11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# string11
    import string
    text = input("Enter a string: ")
    if any(char.isdigit() for char in text):
        print("String contains digits")
    else:
        print("String has no digits")

