# -*- coding: utf-8 -*-
"""string5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# string5
    import string
    text = input("Enter a string: ").lower()
    vowels = 'aeiou'
    vowel_count = sum(1 for char in text if char in vowels)
    consonant_count = sum(1 for char in text if char.isalpha() and char not in vowels)
    print(f"Vowels: {vowel_count}, Consonants: {consonant_count}")

