# -*- coding: utf-8 -*-
"""string16

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# string16
    import string
    text = input("Enter the sentence: ")
    charToRemove=input("Enter what char should be removed: ")
    newText=text.replace(charToRemove,"")
    print(newText)

