# -*- coding: utf-8 -*-
"""string7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# string7
    import string
    text = input("Input sentence: ")
    old=input("Resplace ")
    new=input("with ")
    text = text.replace(old, new)
    print(text)

