# -*- coding: utf-8 -*-
"""string8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# string8
    import string
    text = input("Input the string: ")
    first=text[0]
    last=text[-1]
    print(f"First char of string is {first} and the last one is {last}")

