# -*- coding: utf-8 -*-
"""string12ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# string12
    import string
    text = input("Enter the words: ").split()
    spaceorwhat=input("Enter the space: ")
    print(spaceorwhat.join(text))

