# -*- coding: utf-8 -*-
"""string1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# string1

name=input("Enter you name ")
birthDate=int(input("Enter you birth date "))
currentDate=2025

print(f"Hi {name}, you are {(currentDate-birthDate)} years old")

