# -*- coding: utf-8 -*-
"""string2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

txt = 'LMaasleitbtui'
    cars = ['Audi', 'BMW', 'Toyota', 'Honda']
    found = [car for car in cars if all(letter in txt for letter in car.lower())]
    print("Possible car names:", found)

