# -*- coding: utf-8 -*-
"""string17

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# string17
    import string
    text = input("Enter the sentence: ")
    vowels = 'aeiouAEIOU'
    for vowel in vowels:
        text = text.replace(vowel, "*")
    print(text)

