# -*- coding: utf-8 -*-
"""string9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# string9
    import string
    text = input("Input the string: ")
    reversed=text[::-1]
    print(reversed)

