# -*- coding: utf-8 -*-
"""string14

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# string14
    import string
    text1 = input("Enter the first string: ")
    text2 = input("Enter the second string: ")

    if text1 == text2:
        print("The strings are equal")
    else:
        print("The strings are not equal")

