# -*- coding: utf-8 -*-
"""string4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# string4
    import string
    txt = str(input("Enter a palindrome: "))
    x = txt[::-1]
    if txt == x:
        print(txt, "is a palindrome")
    else:
        print(txt, "is not a palindrome")