# -*- coding: utf-8 -*-
"""string3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ3a4DJtzmHGwbPZAZk7-fKG6jK1gDOy
"""

# string3
    import string
    txt = str(input("Enter a string: "))
    print(len(txt))
    print(txt.upper())
    print(txt.lower())

sd