# -*- coding: utf-8 -*-
"""Employee Manager

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MhpUPZihay1NF6yieSl29uwjKGRndg-p
"""

class Employee:
    def __init__(self, emp_id, name, position, salary):
        self.emp_id = emp_id
        self.name = name
        self.position = position
        self.salary = salary

    def __str__(self):
        return f"{self.emp_id},{self.name},{self.position},{self.salary}"

class EmployeeManager:
    def __init__(self, filename="employees.txt"):
        self.filename = filename

    def add_employee(self, emp):
        with open(self.filename, 'a') as f:
            f.write(str(emp) + '\n')

    def get_employees(self):
        try:
            with open(self.filename, 'r') as f:
                return [line.strip() for line in f]
        except FileNotFoundError:
            return []

    def find_employee(self, emp_id):
        for emp in self.get_employees():
            if emp.startswith(emp_id + ','):
                return emp
        return None

    def run(self):
        while True:
            print("\n1. Add employee\n2. View all\n3. Find by ID\n4. Exit")
            choice = input("Choose: ")

            if choice == '1':
                emp_id = input("ID: ")
                name = input("Name: ")
                position = input("Position: ")
                salary = input("Salary: ")
                self.add_employee(Employee(emp_id, name, position, salary))
                print("Added!")

            elif choice == '2':
                print("\nAll Employees:")
                for emp in self.get_employees():
                    print(emp)

            elif choice == '3':
                emp_id = input("Enter ID: ")
                emp = self.find_employee(emp_id)
                print(emp if emp else "Not found")

            elif choice == '4':
                break
            else:
                print("Your ")

# Start program
manager = EmployeeManager()
manager.run()

