# -*- coding: utf-8 -*-
"""TO DO LIST

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MhpUPZihay1NF6yieSl29uwjKGRndg-p
"""

class Task:
    def __init__(self, task_id, title, status="Pending"):
        self.task_id = task_id
        self.title = title
        self.status = status

    def __str__(self):
        return f"{self.task_id}: {self.title} ({self.status})"

class ToDoApp:
    def __init__(self):
        self.tasks = []

    def add_task(self, task_id, title):
        self.tasks.append(Task(task_id, title))

    def show_tasks(self):
        print("\nTasks:")
        for task in self.tasks:
            print(task)

    def update_status(self, task_id, new_status):
        for task in self.tasks:
            if task.task_id == task_id:
                task.status = new_status
                return True
        return False

    def run(self):
        while True:
            print("\n1. Add task\n2. View tasks\n3. Mark complete\n4. Exit")
            choice = input("Choose: ")

            if choice == '1':
                task_id = input("Task ID: ")
                title = input("Title: ")
                self.add_task(task_id, title)
                print("Added!")

            elif choice == '2':
                self.show_tasks()

            elif choice == '3':
                task_id = input("Task ID to complete: ")
                if self.update_status(task_id, "Completed"):
                    print("Updated!")
                else:
                    print("Task not found")

            elif choice == '4':
                break

# Start program
app = ToDoApp()
app.run()

