# -*- coding: utf-8 -*-
"""Model a Farm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TiOkidaFY9U8ixlxBbcprZuucDwl1ScE

Model a Farm
"""

class Animal:
    def __init__(self, name, species, sound):
        self.name = name
        self.species = species
        self.sound = sound

    def make_sound(self):
        print(f"{self.name} the {self.species} says {self.sound}!")

    def eat(self, food):
        print(f"{self.name} is eating {food}")

class Dog(Animal):
    def __init__(self, name):
        super().__init__(name, "Dog", "Barking")

    def does(self):
        print(f"{self.name} will protect you")

class Hens(Animal):
    def __init__(self, name):
        super().__init__(name, "Hens", "Cluck")

    def lay_egg(self):
        print(f"{self.name} laid an egg!")

class Cat(Animal):
    def __init__(self, name):
        super().__init__(name, "Cat", "Myao")

    def jump(self):
        print(f"{self.name} is jumping on roof!")

class Farm:
    def __init__(self):
        self.animals = []

    def add_animal(self, animal):
        self.animals.append(animal)

    def morning_routine(self):
        print("\nFarm Morning Routine:")
        for animal in self.animals:
            animal.make_sound()
            animal.eat("food")

            # Special behaviors
            if isinstance(animal, Dog):
                animal.does()
            elif isinstance(animal, Hens):
                animal.lay_egg()
            elif isinstance(animal, Cat):
                animal.jump()

        print("\nAll animals are happy!")

# Create and run the farm
farm = Farm()
farm.add_animal(Dog("Reks"))
farm.add_animal(Hens("Margaritta"))
farm.add_animal(Cat("Milky"))
farm.morning_routine()

