# -*- coding: utf-8 -*-
"""Employee Records Manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10b5YxocbmvKhq0V2LnJSa2vxr3bmE8Au
"""

def add_emp():
    with open("employees.txt","a") as f:
        f.write(f"{input('ID: ')},\
        {input('Name: ')}, {input('Position: ')},\
        {input('Salary: ')}\n")

def view_emps():
    try:
        [print(line.strip()) for line in open("employees.txt")]
    except:
        print("No records found")

def search_emp():
    try:
        id = input("Search ID: ")
        [print(line.strip()) for line in open("employees.txt") if line.startswith(id+",")]
    except:
        print("No records found")

def update_emp():
    try:
        id = input("Update ID: ")
        lines = open("employees.txt").readlines()
        with open("employees.txt","w") as f:
            for line in lines:
                if line.startswith(id+","):
                    parts = line.strip().split(", ")
                    parts[1:] = [input(f"New {k}: ") or v for k,v in zip(["Name","Position","Salary"], parts[1:])]
                    line = ", ".join(parts)+"\n"
                f.write(line)
    except: print("No records found")

def delete_emp():
    try:
        id = input("Delete ID: ")
        lines = open("employees.txt").readlines()
        with open("employees.txt","w") as f:
            [f.write(line) for line in lines if not line.startswith(id+",")]
    except: print("No records found")

while True:
    choice = input("\n1.Add 2.View 3.Search 4.Update 5.Delete 6.Exit\nChoice: ")
    if choice == "1": add_emp()
    elif choice == "2": view_emps()
    elif choice == "3": search_emp()
    elif choice == "4": update_emp()
    elif choice == "5": delete_emp()
    elif choice == "6": break