# -*- coding: utf-8 -*-
"""Word Frequency Counter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10b5YxocbmvKhq0V2LnJSa2vxr3bmE8Au
"""

from collections import Counter
import string

def count_words():
    # Read or create file
    try:
        text = open('sample.txt').read().lower()
    except FileNotFoundError:
        text = input("File not found. Enter text: ")
        open('sample.txt', 'w').write(text)

    # Count words (ignoring punctuation)
    words = text.translate(str.maketrans('', '', string.punctuation)).split()
    counts = Counter(words)

    # Display and save results
    print(f"Total words: {len(words)}")
    print("Top words:", counts.most_common(5))

    with open('word_count_report.txt', 'w') as f:
        f.write(f"Total: {len(words)}\nTop words:\n")
        f.writelines(f"{w} - {c}\n" for w, c in counts.most_common(5))

if __name__ == '__main__':
    count_words()

