# -*- coding: utf-8 -*-
"""Zero Check Decorator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10b5YxocbmvKhq0V2LnJSa2vxr3bmE8Au
"""

def check(func):
    def wrapper(a,b):
      if b == 0:
          return "Denominator can't be zero"
      return func(a, b)
    return wrapper


@check
def div(a, b):
   return a / b

print(div(5, 2))
print(div(5, 0))

